import useSWR from "swr";
import {
    Box,
    Button,
    Flex,
    Text,
    Image,
    NumberInput,
    NumberInputField,
    NumberInputStepper,
    NumberIncrementStepper,
    NumberDecrementStepper,
} from "@chakra-ui/react";
import { useRouter } from "next/router";

import Page from "../../../components/Layouts/Page";

const fetcher = async (url) => {
    const res = await fetch(url);
    const data = await res.json();

    if (res.status !== 200) {
        throw new Error(data.message);
    }
    return data;
};

export default function StakeNow({ sidebar }) {
    const { query } = useRouter();
    const { data, error } = useSWR(
        () => query.id && `/api/nfts/${query.id}`,
        fetcher
    );

    if (error) return <div>{error.message}</div>;
    if (!data) return <div>Loading...</div>;

    return (
        <>
            <Page title="Stake Now" sidebar={sidebar}>
                <Box ml="5" mt="5" pl="5" textColor="white">
                    <Text
                        my="2"
                        id="live"
                        fontSize="2xl"
                        fontWeight="bold"
                        textColor="white"
                    >
                        NFT Staking
                    </Text>
                    <Text mb="3" textColor="white" fontWeight="extrabold">
                        Bored Ape Collection
                    </Text>
                    <Box mb="3" boxSize="40vh" objectFit="cover">
                        <Image rounded="md" src={data.bgImage} alt="image" />
                    </Box>

                    <Box
                        textAlign="center"
                        h="10vh"
                        w="40vh"
                        p="2"
                        textColor="white"
                        rounded="md"
                    >
                        <Flex
                            mt="2"
                            fontSize="lg"
                            justifyContent="space-between"
                            alignItems="center"
                        >
                            <Text fontWeight="extrabold">Floor Price</Text>

                            <Flex>
                                <Image
                                    boxSize="20px"
                                    src={data.chainLogo}
                                    alt="eth"
                                />
                                <Text fontWeight="extrabold">
                                    {" "}
                                    {data.value}
                                </Text>
                            </Flex>
                        </Flex>
                    </Box>

                    <Box mt="-3" mb="2" w="40vh">
                        <NumberInput
                            defaultValue={data.value}
                            precision={3}
                            step={0.001}
                        >
                            <NumberInputField />

                            <NumberInputStepper>
                                <NumberIncrementStepper />
                                <NumberDecrementStepper />
                            </NumberInputStepper>
                        </NumberInput>
                    </Box>
                    <Flex w="40vh" justifyContent="space-between">
                        <Button
                            bgColor="#1638B0"
                            w="100px"
                            h="50px"
                            _hover="none"
                            textColor="white"
                            fontWeight="extrabold"
                        >
                            Long
                        </Button>
                        <Button
                            bgColor="#C20B0B"
                            w="100px"
                            h="50px"
                            _hover="none"
                            textColor="white"
                            fontWeight="extrabold"
                        >
                            Short
                        </Button>
                    </Flex>

                    <Box textColor="white">
                        <Text mt="5" fontWeight="extrabold" fontSize="lg">
                            Description
                        </Text>

                        <Box mt="3" fontSize="sm" textColor="gray.500">
                            <Text>
                                Bored Ape Yacht Club (BAYC), or often
                                colloquially called Bored Ape, is a non-fungible
                                token (NFT) collection built on the Ethereum
                                blockchain. The collection features profile
                                pictures of cartoon apes that are procedurally
                                generated by an algorithm.
                            </Text>
                            <br />
                            <Text>
                                Yuga Labs is the parent company of Bored Ape
                                Yacht Club.[1] The project launched with a live
                                pre-sale on April 23, 2021.[2] Owners of a Bored
                                Ape NFT are granted access to a private online
                                club, exclusive in-person events, and
                                intellectual property rights for the image.
                            </Text>
                        </Box>
                    </Box>
                </Box>
            </Page>
        </>
    );
}
