import {
  Box,
  Button,
  Flex,
  Text,
  Image,
  Spacer,
  NumberInput,
  NumberInputField,
  NumberInputStepper,
  NumberIncrementStepper,
  NumberDecrementStepper,
} from "@chakra-ui/react";
import React from "react";
import Page from "../../../components/Page";

export default function stakeNow({ sidebar }) {
  return (
    <>
      <Page title="Stake Now" sidebar={sidebar}>
        <Box ml="5" mt="5" pl="5" textColor="white">
          <Text
            my="2"
            id="live"
            fontSize="2xl"
            fontWeight="bold"
            textColor="white"
          >
            NFT Staking
          </Text>
          <Text mb='3' textColor="white" fontWeight="extrabold">
            Bored Ape Collection
          </Text>
          <Box mb='3' boxSize="50vh" objectFit="cover">
            <Image rounded='md' src="/widget1.png" alt="image" />
          </Box>

          <Box
            mb="2"
            textAlign="center"
            h="10vh"
            w="50vh"
            p="2"
            textColor="white"
            rounded="md"
          >
            <Flex fontSize="lg" justifyContent="space-between" alignItems='center'>
              <Text  fontWeight="extrabold">
                Floor Price
              </Text>

              <Spacer></Spacer>

              <Image boxSize="20px" src={"/eth.png"} alt="eth" />

              <Text fontWeight="extrabold"> 3.5</Text>
            </Flex>
          </Box>

          <Box mb="4" w="50vh">
            <NumberInput defaultValue={15} precision={2} step={0.2}>
              <NumberInputField />

              <NumberInputStepper>
                <NumberIncrementStepper />
                <NumberDecrementStepper />
              </NumberInputStepper>

            </NumberInput>
          </Box>

          <Button bgColor="#1638B0" w="50vh" _hover="none">
            <Text textColor="white" fontWeight="extrabold">
              Stake Now
            </Text>
          </Button>

          <Box textColor="white">
            <Text mt="5" fontWeight="extrabold" fontSize="lg">
              Description
            </Text>

            <Text mt="3" fontSize="sm" textColor="gray.500">
              <p>
                Bored Ape Yacht Club (BAYC), or often colloquially called Bored
                Ape, is a non-fungible token (NFT) collection built on the
                Ethereum blockchain. The collection features profile pictures of
                cartoon apes that are procedurally generated by an algorithm.
              </p>
              <br />
              <p>
                Yuga Labs is the parent company of Bored Ape Yacht Club.[1] The
                project launched with a live pre-sale on April 23, 2021.[2]
                Owners of a Bored Ape NFT are granted access to a private online
                club, exclusive in-person events, and intellectual property
                rights for the image.
              </p>
            </Text>

          </Box>
        </Box>
      </Page>
    </>
  );
}
